### ISSUE TITLE
Error while inserting custom flatten layer in model.py of inceptionv3 core layer in keras engine

### ISSUE THREAD

**Issue by tejasri19** [Gogul09/flower-recognition#13]
Traceback (most recent call last): File "extract_features.py", line 73, in <module> model = Model(input=base_model.input, output=base_model.get_layer('custom').output) File "/home/isemes/anaconda3/envs/tensorflow-venv/lib/python3.6/site-packages/keras/engine/network.py", line 364, in get_layer raise ValueError('No such layer: ' + name) ValueError: No such layer: custom

**Comment by Kohimax** [comment]
I face the same issue

**Comment by Kohimax** [comment]
The problem is resolved after re-install the keras
